name: Crawl and Clean Jobs

on:
  schedule:
    - cron: '0 9 * * *' # Every day at 9 AM UTC
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci
          npm install --save-dev ts-node@latest typescript @types/node dotenv

      - name: Run crawler with ts-node-esm
        env:
          FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}
        run: node --loader ts-node/esm ./src/fetchJobs.ts

      - name: Commit and push jobs.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add jobs.json || echo "No jobs.json found"
          git commit -m "Update jobs.json" || echo "Nothing to commit"
          git push origin main
